name: Generate Snake
on:
  schedule: [{ cron: "0 0 * * *" }]    # 매일 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: pghoya2956
          outputs: |
            output/snake.svg
