name: Generate Snake
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3 
        with:
          github_user_name: pghoya2956
          outputs: |
            output/snake.svg
          # (선택) 색상·배경 커스터마이즈 예시
          # palette:     "#8ecdff #2d81ff #041b38 #ffffff"
          # snake_color: "#00ff99"
